# Generated by Django 3.2.3 on 2021-05-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20210516_0535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='places',
            name='genres',
        ),
        migrations.AddField(
            model_name='places',
            name='genres',
            field=models.ManyToManyField(blank=True, null=True, to='places.Genres'),
        ),
    ]
