# Generated by Django 3.2.3 on 2021-06-10 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_auto_20210602_0456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentlikes',
            options={'ordering': ('created_at',), 'verbose_name': 'Comment Like', 'verbose_name_plural': 'Comment Likes'},
        ),
        migrations.AlterField(
            model_name='commentlikes',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places_comment_likes', to='places.places'),
        ),
        migrations.AlterField(
            model_name='images',
            name='img',
            field=models.ImageField(upload_to='files/notifications', verbose_name='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='places',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='places_genres', to='places.Genres'),
        ),
    ]
