# Generated by Django 3.2.3 on 2021-06-10 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_images_img_render'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='img_feature',
        ),
    ]
