# Generated by Django 3.2.4 on 2021-07-12 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('places', '0012_remove_images_img_feature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='places',
            name='address',
        ),
        migrations.AddField(
            model_name='places',
            name='coordinates',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='places.coordinates'),
        ),
        migrations.AddField(
            model_name='places',
            name='img_render',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='places',
            name='description',
            field=models.TextField(max_length=300, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='places',
            name='img',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='places.images'),
        ),
    ]
