# Generated by Django 3.2.4 on 2021-07-01 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('places', '0012_remove_images_img_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='img',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wagtailimages.image'),
        ),
    ]
