# Generated by Django 3.2.4 on 2021-07-01 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('places', '0013_alter_places_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='img_render',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='places',
            name='img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='places.images'),
        ),
    ]
