# Generated by Django 3.2.4 on 2021-07-13 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0013_auto_20210712_1651'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
