# Generated by Django 3.2.4 on 2021-07-01 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0014_auto_20210701_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='places',
            name='img',
        ),
    ]
