# Generated by Django 3.2.4 on 2021-07-13 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('places', '0014_delete_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='places.images'),
        ),
        migrations.AlterField(
            model_name='places',
            name='img_render',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wagtailimages.image'),
        ),
    ]
