# Generated by Django 3.2.4 on 2021-07-01 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0015_remove_places_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='img',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='places.images'),
        ),
    ]
