# Generated by Django 3.2.4 on 2021-07-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0017_remove_places_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='description',
            field=models.TextField(max_length=300, verbose_name='Description'),
        ),
    ]
