# Generated by Django 3.2.4 on 2021-07-09 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0018_alter_places_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='coordinates',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='places.coordinates'),
        ),
    ]
