version: "3.8"

networks:
  app_maltalovers:

services:
  django:
    build: .
    container_name: app_maltalovers
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
    - .:/usr/src/app
    ports:
    - "8000:8000"
    networks:
    - app_maltalovers

