# Generated by Django 3.2.4 on 2021-07-01 18:16

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0012_remove_images_img_feature'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Titulo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Un Tipo de Actividades',
                'verbose_name_plural': 'Tipos de Actividades',
            },
        ),
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('file', models.FileField(upload_to='files/notifications', verbose_name='Archivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telephone')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Direction')),
                ('city', models.TextField(blank=True, null=True, verbose_name='City')),
                ('country', models.TextField(blank=True, null=True, verbose_name='Country')),
                ('account_status', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.OneToOneField(help_text='Owner', on_delete=django.db.models.deletion.CASCADE, related_name='owner_listing', to=settings.AUTH_USER_MODEL)),
                ('places', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_listing', to='places.places')),
            ],
            options={
                'verbose_name': 'Listing',
                'verbose_name_plural': 'Listings',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='BusinessName')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserHelper',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ListingAdmin',
            fields=[
                ('user', models.OneToOneField(help_text='Usuario', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student_parent_profile', serialize=False, to='auth.user')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefono')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('city', models.TextField(blank=True, null=True, verbose_name='Ciudad')),
                ('country', models.TextField(blank=True, null=True, verbose_name='País')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listings', models.ManyToManyField(help_text='Lugares', to='listing.Listing')),
            ],
            options={
                'verbose_name': 'Representante',
                'verbose_name_plural': 'Representantes',
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='BusinessName')),
                ('vat', models.CharField(blank=True, max_length=20, null=True, verbose_name='VAT')),
                ('business_email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20, verbose_name='Telephone')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Direction')),
                ('city', models.TextField(blank=True, null=True, verbose_name='City')),
                ('country', models.TextField(blank=True, null=True, verbose_name='Country')),
                ('business_type', models.SmallIntegerField(choices=[(0, 'Registered Single Business'), (0, 'Registered Multiple Business'), (1, 'Self-Employed'), (2, 'Individual - Taxes on personal income'), (3, 'Non-profit Organization'), (4, 'Government Organization'), (5, 'Private Organization'), (5, 'Public Organization')], verbose_name='Business Type')),
                ('account_type', models.SmallIntegerField(choices=[(0, 'Business with Listings'), (1, 'Service Provider'), (2, 'Influencer')], verbose_name='Account Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_sector', to='listing.sector')),
            ],
        ),
    ]
