# Generated by Django 3.2.4 on 2021-06-18 19:49

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Titulo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Un Tipo de Actividades',
                'verbose_name_plural': 'Tipos de Actividades',
            },
        ),
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('file', models.FileField(upload_to='files/notifications', verbose_name='Archivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('user', models.OneToOneField(help_text='Usuario', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student_profile', serialize=False, to='auth.user')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('city', models.TextField(blank=True, null=True, verbose_name='Ciudad')),
                ('country', models.TextField(blank=True, null=True, verbose_name='País')),
                ('account_status', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Estatus')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dia de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'db_table': 'courses_students',
            },
        ),
        migrations.CreateModel(
            name='UserHelper',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ListingAdmin',
            fields=[
                ('user', models.OneToOneField(help_text='Usuario', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student_parent_profile', serialize=False, to='auth.user')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefono')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('city', models.TextField(blank=True, null=True, verbose_name='Ciudad')),
                ('country', models.TextField(blank=True, null=True, verbose_name='País')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listings', models.ManyToManyField(help_text='Lugares', to='listing.Listing')),
            ],
            options={
                'verbose_name': 'Representante',
                'verbose_name_plural': 'Representantes',
            },
        ),
    ]
