# Generated by Django 3.2.4 on 2021-06-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='BusinessName')),
                ('vat', models.CharField(blank=True, max_length=20, null=True, verbose_name='VAT')),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20, verbose_name='Telephone')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Direction')),
                ('city', models.TextField(blank=True, null=True, verbose_name='City')),
                ('country', models.TextField(blank=True, null=True, verbose_name='Country')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='BusinessName')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='account_type',
            field=models.SmallIntegerField(choices=[(0, 'Business with Listings'), (1, 'Service Provider'), (2, 'Influencer')], default=1, verbose_name='Dia de semana'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='business_type',
            field=models.SmallIntegerField(choices=[(0, 'Registered Single Business'), (0, 'Registered Multiple Business'), (1, 'Self-Employed'), (2, 'Individual - Taxes on personal income'), (3, 'Non-profit Organization'), (4, 'Government Organization'), (5, 'Private Organization'), (5, 'Public Organization')], default=1, verbose_name='Dia de semana'),
            preserve_default=False,
        ),
    ]
