# Generated by Django 3.2.4 on 2021-06-18 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_auto_20210618_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='sector',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='business_sector', to='listing.sector'),
            preserve_default=False,
        ),
    ]
