# Generated by Django 3.2.4 on 2021-07-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_openinghours'),
    ]

    operations = [
        migrations.AddField(
            model_name='openinghours',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
