# Generated by Django 3.2.4 on 2021-07-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_openinghours_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='openinghours',
            name='open_all_day',
            field=models.BooleanField(default=False),
        ),
    ]
