# Generated by Django 3.2.4 on 2021-06-18 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_auto_20210618_2206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='email',
            new_name='business_email',
        ),
    ]
