# Generated by Django 3.1.6 on 2021-02-05 18:47

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='banner_background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cards',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('cta_1', wagtail.core.blocks.URLBlock(required=False)), ('cta_2', wagtail.core.blocks.URLBlock(required=False)), ('cards', wagtail.core.blocks.StructBlock([('header', wagtail.core.blocks.CharBlock(form_classname='full title')), ('body', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('cta_1', wagtail.core.blocks.URLBlock(required=False)), ('cta_2', wagtail.core.blocks.URLBlock(required=False))], required=False))], blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_1',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_2',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='header',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='subheading',
            field=models.TextField(blank=True),
        ),
    ]
